#!/bin/bash

iconmaker=$(basename $0)
_TMP=$(PWD)/.tmp_iconmaker


function usage {
  cat <<EOM
Usage: ${iconmaker} [OPTION]...
  -h            Display help
  -t VALUE      Put text to annotate
  -i VALUE      Select image
  -s VALUE      Select seal
EOM

  exit 
}



while getopts ":t:i:s:h" opt; do
  case "$opt" in
    t)
      t="$OPTARG"
      ;;
    i)
      i="$OPTARG"
      ;;
    s)
      s="$OPTARG"
      ;;
 

    '-h'|'--help'|* )
      usage
      ;;
  esac
done


rm -Rf ${_TMP}
mkdir -p ${_TMP}
cp -ip $i ${_TMP}
cp -ip $s ${_TMP} 
docker run --rm -v ${_TMP}:/root/tmp-dir --env TAG=$t --env IMG=$i --env SLN=$s rhemsjapan/iconmaker:develop
mv -f ${_TMP}/`echo $i | cut -d '.' -f 1`-iconmaker.png ./
rm -Rf ${_TMP}